
DROP USER IF EXISTS datagouvmaster;
CREATE ROLE datagouvmaster WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'Datagouv$2021';

CREATE DATABASE datagouv
    WITH 
    OWNER = datagouvmaster
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE datagouv TO datagouvmaster WITH GRANT OPTION;